Fix: #497 Baidu Translator: failed to translate chinses to japanese
dotnet/ResXResourceManager pull request #498
Opened 2022-09-21 16:04 UTC by zergmk2

2022-09-21 16:04 UTC, dnfadmin commented
[![CLA assistant check](https://cla.dotnetfoundation.org/pull/badge/not_signed)](https://cla.dotnetfoundation.org/dotnet/ResXResourceManager?pullRequest=498) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/ResXResourceManager?pullRequest=498) before we can accept your contribution.<br/><br/>:x: zergmk2 [sign now](https://cla.dotnetfoundation.org/dotnet/ResXResourceManager?pullRequest=498)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/ResXResourceManager?pullRequest=498) it.</sub>

2022-09-21 17:46 UTC, tom-englert requested changes

2022-09-21 17:46 UTC, tom-englert commented on src/ResXManager.Translators/BaiduTranslator.cs
> +            if (_baiduCultureMap.ContainsKey(targetCulture.TwoLetterISOLanguageName))
Use TryGetValue

2022-09-22 01:04 UTC, zergmk2 commented on src/ResXManager.Translators/BaiduTranslator.cs
> +            if (_baiduCultureMap.ContainsKey(targetCulture.TwoLetterISOLanguageName))
Done. Thanks.

2022-09-23 06:02 UTC, merged

2023-07-09 09:18 UTC, 632575987 commented
failed to translate zh-Hans to zh-Hant.